#!/usr/bin/env python3
"""Build step for the SOC Operations Training Platform.

Merges the authored JSON in data/ into the JS bundles the app loads, and
splits every answer key out of the public payload into an encoded blob so
that no answer is readable in page source or dev tools "sources" view.

Run:  python3 build.py

NOTE: this project uses a FLAT layout - every file (authored data JSON,
generated JS bundles, HTML, CSS, images) lives directly in this same
folder. There are no data/ or js/ subfolders.
"""
import base64
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
DATA = ROOT
JS = ROOT

# Fields that must never be shipped in the public level payload.
KEY_FIELDS = ("decision", "severity_answer", "recommend", "timelineKey",
              "review", "hints", "quizBank")


def load(name):
    with open(os.path.join(DATA, name), encoding="utf-8") as fh:
        return json.load(fh)


def main():
    levels = []
    for part in ("levels_a", "levels_b", "levels_c", "levels_d"):
        levels += load(part + ".json")
    master = load("levels_master.json")
    levels += master if isinstance(master, list) else [master]
    levels.sort(key=lambda l: l["id"])

    ids = [l["id"] for l in levels]
    assert ids == list(range(1, 31)), "expected levels 1..30, got %r" % ids

    public, keys = [], {}

    for lv in levels:
        pub = {k: v for k, v in lv.items()
               if k not in KEY_FIELDS and k != "questions"}
        pq, kq = [], []
        for q in lv["questions"]:
            item = {"id": q["id"], "label": q["label"], "type": q["type"]}
            if q.get("options"):
                item["options"] = q["options"]
            if q.get("placeholder"):
                item["placeholder"] = q["placeholder"]
            pq.append(item)
            kq.append({"id": q["id"], "type": q["type"],
                       "accept": q.get("accept", []),
                       "hint": q.get("hint", "")})
        pub["questions"] = pq
        pub["qCount"] = len(pq)

        # Optional richer training-flow fields (theory chapters / MCQ bank /
        # guided investigation). "chapters" and "guided" are teaching content
        # and ship in full in the public payload. "quizBank" has its correct
        # answers stripped out the same way "questions" does above, so the
        # knowledge-test answer key never sits beside the questions.
        qb = lv.get("quizBank")
        if qb:
            pubQuiz, keyQuiz = [], []
            for mq in qb:
                pubQuiz.append({"id": mq["id"], "q": mq["q"], "options": mq["options"]})
                keyQuiz.append({"id": mq["id"], "correct": mq["correct"], "explain": mq.get("explain", "")})
            pub["quizBank"] = pubQuiz
        else:
            keyQuiz = []

        public.append(pub)

        keys[str(lv["id"])] = {
            "questions": kq,
            "decision": lv.get("decision"),
            "severity": lv.get("severity_answer"),
            "recommend": lv.get("recommend", {}),
            "timelineKey": lv.get("timelineKey", []),
            "review": lv.get("review", ""),
            "hints": lv.get("hints", []),
            "quiz": keyQuiz,
        }

    book = []
    for part in ("book_a", "book_b", "book_c"):
        book += load(part + ".json")
    book.sort(key=lambda c: c["id"])
    assert [c["id"] for c in book] == list(range(1, 31)), "expected 30 chapters"

    commands = load("commands.json")

    blob = base64.b64encode(
        json.dumps(keys, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    ).decode("ascii")

    def write(name, body):
        path = os.path.join(JS, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(body)
        print("  %-14s %7.1f KB" % (name, os.path.getsize(path) / 1024.0))

    dump = lambda o: json.dumps(o, ensure_ascii=False, separators=(",", ":"))

    print("build:")
    write("levels.js", "/* generated by build.py - do not edit */\n"
                       "window.LEVELS=" + dump(public) + ";\n")
    write("book.js", "/* generated by build.py - do not edit */\n"
                     "window.BOOK=" + dump(book) + ";\n")
    write("commands.js", "/* generated by build.py - do not edit */\n"
                         "window.COMMANDS=" + dump(commands) + ";\n")
    write("eval.js", "/* generated by build.py - evaluation payload (encoded) */\n"
                     "window.EVAL_B64=\"" + blob + "\";\n")

    qtotal = sum(l["qCount"] for l in public)
    print("  %d levels, %d questions, %d chapters, %d commands"
          % (len(public), qtotal, len(book), len(commands)))


if __name__ == "__main__":
    main()
